name: build, test and deploy

on:
  push:
    branches:
        - main

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ColorHelper
      run: dotnet restore
      
    - name: Build
      working-directory: ColorHelper
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ColorHelper
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish .NET Core Project
      run: dotnet publish ColorHelper/ColorHelperUi/ColorHelperUi.csproj -c Release -o release --nologo
      
    # changes the base-tag in index.html from '/' to 'ColorHelperUi' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to ColorHelperUi
      run: sed -i 's/<base href="\/" \/>/<base href="\/ColorHelperUi\/" \/>/g' release/wwwroot/index.html
    
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ColorHelper/release/wwwroot
